test-cases/call_unknown.wybe:1:24: Call to unknown 'nonexistent_proc' from foo
